function config = default_lrt_ddce_pipeline_config()
% default_lrt_ddce_pipeline_config  Defaults for run_lrt_ddce_pipeline.
%
% Typical use:
%   config = default_lrt_ddce_pipeline_config();
%   config.reconMatPath = '/path/to/recon_results.mat';
%   config.outputDir = '/path/to/output';
%   config.sequencePreset = 'vtr240';
%   config.sequence.linesPerShot = 240;
%   outputs = run_lrt_ddce_pipeline(config);

config = struct();

config.reconMatPath = '';
config.outputDir = '';
config.dceCodeDir = '/Users/jameszhang/Documents/RYLab/src/DCE_MOCO';
config.startStage = 't1';

config.sequencePreset = 'vtr';
config.sequence = struct( ...
    'linesPerShot', [], ...
    'cutoff', [], ...
    'TR', [], ...
    'TR1', [], ...
    'TR2', [], ...
    'TI', [], ...
    'flipAngleDeg', [], ...
    'reps', [], ...
    'minT1', [], ...
    'maxT1', [], ...
    'numT1', [], ...
    'reconNEco', [], ...
    'dictOptions', struct(), ...
    'params', struct(), ...
    'fitParams', struct());
config.cardiacPhases = 24;
config.respPhase = 1;
config.sliceIndices = [];
config.timeIndices = [];

config.maskMode = 'reuse_or_draw';
config.t1MaskPath = '';
config.dceSliceIndices = [];
config.dceOptionalRois = false;

config.precontrastT1Ms = 1350;
config.precontrastT1MapPath = '';
config.timeMinutes = 1:10;
config.fitPoints = 1:10;
config.gdRelaxivity = 4.97;

config.models = {'2CXM', 'ETK'};
config.synthesisEndMinutes = 30;
config.synthesisStepMinutes = 1;
config.synthesisScaleFactors = 1;
config.exportSynthDicom = false;
config.synthDicomRoot = '/Volumes/Extreme SSD/Anzhen/DICOM/New0123456amidicom64';
config.synthDicomLookupFile = '/Volumes/Extreme SSD/Anzhen/AMI/AMI20260207_Anonymized.xlsx';
config.synthDicomOutputDir = '';
config.synthDicomLgeSeriesDescriptionContains = 'sax_MAG';
config.synthDicomScaleMax = 4095;
config.synthDicomWindowCenter = 2048;
config.synthDicomWindowWidth = 4095;

config.saveQc = true;
config.orientationTransform = {'rot90ccw', 'flip_lr'};

config.aifInitial = struct( ...
    'B', 3.1987, ...
    'a1', 6.4922, ...
    'a2', 0.5935, ...
    'm1', 0.1196, ...
    'm2', 43.7633, ...
    'sigma1', 0.1741, ...
    'sigma2', 0.2162, ...
    'mu1', 0.2618, ...
    'mu2', 0.7021, ...
    'tc', 0.1504, ...
    'Sf', 1);

config.fit2CXM = struct( ...
    'x0', [0.5 1.0 0.04 0.15], ...
    'lb', [0.2 0.0001 0.0 0.001], ...
    'ub', [2 3 1 1], ...
    'targetR2', 0.9, ...
    'maxIterations', 1);

config.fitETK = struct( ...
    'x0', [0.06 0.005 0.15], ...
    'lb', [0 0 0], ...
    'ub', [1 1 1], ...
    'targetR2', 0.9, ...
    'maxIterations', 5, ...
    'omitTimeIndex', 2);

end
