function [imageOut,interpFactor] = interp2dimage(image,target,targetType,twixObj)
% 2D interpolation of images of size [Ny,Nx,:] to [Nynew,Nxnew,:]
%
% Input:
%       image       - multi-dimension array of size [Ny,Nx,N3,N4,...]
%
%       target      - 1x2 array, interpolation factor / new image size
%                     / new resolution
%
%       targetType  - (default is 'factor')
%                     'factor'    :[Nynew Nxnew] = target.*[Ny Nx]
%                     'matrix'    :[Nynew Nxnew] = target
%                     'resolution':[Nynew Nxnew] = [old resol./target].*[Ny Nx]
%                     [Nynew Nxnew] will be floored.
%
%       twixObj     - Original spacial resolution info
%                     Siemens data header generated by mapVBVD()
%                     Or can be a 1x2 array of resolution in mm
%                     
% Output:
%       imageOut     - interpolated image
%
%       interpFactor - 1x2 array of the actual interpolation factor
%

if nargin < 3
    targetType = 'factor';
end

try
    Ny = size(image,1);
    Nx = size(image,2);

    switch targetType
        case 'factor'
            Nynew = floor(Ny*target(1));
            Nxnew = floor(Nx*target(2));
            interpFactor = [Nynew Nxnew]./[Ny Nx];
            imageOut = imresize(image,[Nynew Nxnew]);
        case 'matrix'
            Nynew = target(1);
            Nxnew = target(2);
            interpFactor = [Nynew Nxnew]./[Ny Nx];   
            imageOut = imresize(image,[Nynew Nxnew]);
        case 'resolution'
            try
                % Spatial resolution
                if isfield(twixObj,'hdr')
                    asSlice = twixObj.hdr.MeasYaps.sSliceArray.asSlice{1};
                    pixelSpacing = [asSlice.dPhaseFOV/twixObj.hdr.Config.NImageLins;asSlice.dReadoutFOV/twixObj.hdr.Dicom.lBaseResolution]; 
                else
                    pixelSpacing = target;
                end
                interpFactor = pixelSpacing(:)./target(:);
                Nynew = floor(Ny*interpFactor(1));
                Nxnew = floor(Nx*interpFactor(2));
                interpFactor = [Nynew Nxnew]./[Ny Nx];  
                imageOut = imresize(image,[Nynew Nxnew]);
            catch
                imageOut = image;
                interpFactor = [1 1];
                disp('No protocol resolution info! return original image.');
            end
    end
catch
    imageOut = image;
    interpFactor = [1 1];
    disp('Interpolation error! Return original image.');
end
