function curve = plotFitResult(fitResult,slice,cIdx)
% ========================================================================
%
% Plot image curve and fitted curve of selected voxel
%
%   Input:
%
%       fitResult  - fitting result generated by paramFit
%
%       slice  - display slice number, default is center slice
%
%       cIdx   - cardiac phase number, default is 1
%
%   Output:
%
%       curve  - image and fitted curves of the current voxel
%
%
%  - 2023-04-12
%  - Created by Hsu-Lei Lee @ BIRI, Cedars-Sinai Medical Center
%
% ========================================================================

% extractVarFromStruct(fitResult);
extractVarFromStruct(fitResult.fitParams);

[Nydisp,Nxdisp,Nzdisp,Np] = size(fitResult.T1map);

fitResult.T1map = imageOrientLPS(fitResult.T1map,params);
fitResult.T2map = imageOrientLPS(fitResult.T2map,params);
fitResult.T1rhomap = imageOrientLPS(fitResult.T1rhomap,params);
fitResult.BIRmap = imageOrientLPS(fitResult.BIRmap,params);
fitResult.BT2map = imageOrientLPS(fitResult.BT2map,params);
fitResult.B1map  = imageOrientLPS(fitResult.B1map,params);
fitResult.Avpmap = imageOrientLPS(fitResult.Avpmap,params);
fitResult.mask   = imageOrientLPS(fitResult.mask,params);

extractVarFromStruct(fitResult);

if nargin < 3 || cIdx > Np || cIdx < 1
    cIdx = 1;
end

if nargin < 2 || isempty(slice) || slice < 1 || slice > Nzdisp
    slice = floor(size(T1map,3)/2) + 1;
end

if ~exist('ns','var')
    ns = 1:Nseg;
    fitResult.fitParams.ns = ns;
end
totaln  = numel(ns);
Nsegnew = zeros(1,totaln*moduleLength);
for ii = 1: moduleLength
    temp = (ii-1)*Nseg + ns;
    Nsegnew((ii-1)*totaln+(1:totaln)) = temp;
end

cphase = cphases(cIdx);
Necho = size(Phi,6);
L = size(Gr,1);
tempNecho = size(Phi,1)/L;
Phi = Phi(1:tempNecho:end,:,:,:,:,1);
U = U(:,:,:,1:tempNecho:end,:);
PhiT1 = Gr\reshape(Phi(:,Nsegnew,cphase,rphase,:),L,[]);
recon = reshape(reshape(U(:,:,slice,:),[],L)*PhiT1,Nydisp,Nxdisp,[]);
A = max(abs(recon(:)));
recon = recon./A;
fitResult.Avpmap = fitResult.Avpmap./A;

recon_re = real(recon); recon_re = imageOrientLPS(recon_re,params);
recon_im = imag(recon); recon_im = imageOrientLPS(recon_im,params);
recon = recon_re + 1j*recon_im;

%cmap = 'gray';
cmap = warmmetal;
ylim = [-1 1];

figure; af = gcf;
subplot(1,2,1);displayImage(wmedfilt2(T1map(:,:,slice,cIdx))*1000,[0 maxT1*1000],cmap);

title('Click on a pixel to show signal curve');drawnow;
ax = gca;
h = impoint(ax);
position = round(h.getPosition);
curve = realify(squeeze(recon(position(2),position(1),:)));
curve = curve./sign(curve(end));
curve = curve(:);
strTitle = sprintf('voxel = (%d,%d)',position(1),position(2));

if (mask(position(2),position(1),slice)>0)
    switch ScanType
        case {'IR','SR'}
            curve2 = simCurve_T1_1FA(fitResult,[position(2),position(1),slice],cIdx,curve(:).');
        case {'IR_VFA','SR_VFA'}
            curve2 = simCurve_T1_VFA(fitResult,[position(2),position(1),slice],cIdx,curve(:).');
        case {'Cine'}
            curve2 = zeros(size(curve));
        otherwise
            curve2 = simCurve_T1rhoT2IRVFA(fitResult,[position(2),position(1),slice],cIdx,curve(:).');
            %curve2 = simCurve_T1T2_1FA(recon2,[position(2),position(1),slice],cIdx,curve(:).');
            %curve2 = simCurve_T1T2_2FA(recon2,[position(2),position(1),slice],cIdx,curve(:).');
    end
    strTitle = sprintf('%s, T1 = %d',strTitle,round(1000*T1map(position(2),position(1),slice,cIdx)));
    if isfield(fitResult,'fitParams') && fitResult.fitParams.numT2prep > 0
        strTitle = sprintf('%s, T2 = %d',strTitle,round(1000*T2map(position(2),position(1),slice,cIdx)));
    end
    if isfield(fitResult,'fitParams') && fitResult.fitParams.numT1rhoPrep > 0
        strTitle = sprintf('%s, T1rho = %d',strTitle,round(1000*T1rhomap(position(2),position(1),slice,cIdx)));
    end
    if isfield(fitResult,'BIRmap')
        strTitle = sprintf('%s, B = %.2f',strTitle,BIRmap(position(2),position(1),slice,cIdx));
    end
    if isfield(fitResult,'B1map')
        strTitle = sprintf('%s, beta = %.2f',strTitle,B1map(position(2),position(1),slice,cIdx));
    end
    strTitle2 = 'Blue: data, Red: fitted curve';

    curve(:,2) = curve2(:);
else
    strTitle2 = 'Blue: data, no fitted curve';
    curve(:,2) = 0;
end

figure(af);subplot(1,2,2);plot(curve,'.-');title(strTitle2);
axis([0 size(recon,3) ylim]);grid on;
title(ax,strTitle);

addNewPositionCallback(h,@(h) updateCurve(h,recon,af,ax,ylim,slice,fitResult,cIdx));


function curve = updateCurve(position,recon,af,ax,ylim,slice,fitResult,cIdx)
position = round(position);
if sum(~isfinite(squeeze(recon(position(2),position(1),:)))) == 0
    curve = realify(squeeze(recon(position(2),position(1),:)));
    curve = curve./sign(curve(end));
else
    curve = zeros(squeeze(recon(position(2),position(1),:)));
end
curve = curve(:);
strTitle = sprintf('voxel = (%d,%d)',position(1),position(2));

if (fitResult.mask(position(2),position(1),slice)>0)
    switch fitResult.fitParams.ScanType
        case {'IR','SR'}
            curve2 = simCurve_T1_1FA(fitResult,[position(2),position(1),slice],cIdx,curve(:).');
        case {'IR_VFA','SR_VFA'}
            curve2 = simCurve_T1_VFA(fitResult,[position(2),position(1),slice],cIdx,curve(:).');
        case {'Cine'}
            curve2 = zeros(size(curve));
        otherwise
            curve2 = simCurve_T1rhoT2IRVFA(fitResult,[position(2),position(1),slice],cIdx,curve(:).');
            %curve2 = simCurve_T1T2_1FA(recon2,[position(2),position(1),slice],cIdx,curve(:).');
            %curve2 = simCurve_T1T2_2FA(recon2,[position(2),position(1),slice],cIdx,curve(:).');
    end
    strTitle = sprintf('%s, T1 = %d',strTitle,round(1000*fitResult.T1map(position(2),position(1),slice,cIdx)));
    if isfield(fitResult,'T2map')
        strTitle = sprintf('%s, T2 = %d',strTitle,round(1000*fitResult.T2map(position(2),position(1),slice,cIdx)));
    end    
    if isfield(fitResult,'BIRmap')
        strTitle = sprintf('%s, B = %.2f',strTitle,fitResult.BIRmap(position(2),position(1),slice,cIdx));
    end
    if isfield(fitResult,'B1map')
        strTitle = sprintf('%s, beta = %.2f',strTitle,fitResult.B1map(position(2),position(1),slice,cIdx));
    end
    strTitle2 = 'Blue: data, Red: fitted curve';
    curve(:,2) = curve2(:);
else
    strTitle2 = 'Blue: data, no fitted curve';
    curve(:,2) = 0;
end
figure(af);subplot(1,2,2);
ax2 = gca;
%titleStr = ax2.Title.String;
plot(curve,'.-');title(strTitle2);
axis([0 size(recon,3) ylim]);grid on;
%title(ax2,titleStr);
title(ax,strTitle);
